# Associate boundaries to obstacle tag IDs
obstacles : [
  {id: 1, bounds: [2, 1]}, # car
  {id: 2, bounds: [1.0, 1.0]} # person
]

# Boundaries that contain this world
boundaries: {
  top_left: [2.8, 7.2], 
  bot_right: [-10.4, -5.7]
}

# Associate goal and start with tag ID
goal: 3
start: 0

# Dimensions of grid
width: 80
height: 200
